### ISSUE TITLE
Layout decente para el admin

### ISSUE THREAD

**Issue by desarrolla2** [symfony-madrid/symfony-madrid#10]
Incluir algún layout en el admin bundle, que ahora está que da pena.

**Comment by Osukaru** [comment]
Si, tenía pensado meterle el twitter bootstráp, en Symfony-bcn lo han puesto.
------Mensaje original------
De: Daniel González
Para: Oscar Lopez
Asunto: [symfony-madrid] Layout decente para el admin (#10)
Enviado: 28 de mar de 2012 12:40

Incluir algún layout en el admin bundle, que ahora está que da pena.

---

Reply to this email directly or view it on GitHub:
https://github.com/symfony-madrid/symfony-madrid/issues/10

Enviado desde mi BlackBerry® de Vodafone

**Comment by desarrolla2** [comment]
Quizá fuera una buena idea separar todo el backend en otro Bundle ...
