### ISSUE TITLE
Modificaciones en la web

### ISSUE THREAD

**Issue by desarrolla2** [symfony-madrid/symfony-madrid#6]
Hola chicos.

Si nadie tiene nada en contra voy a realizar los siguientes cambios en la web.

CSS, tiene algunos errores,
1.- el netbeans me marca como error a :hover en lugar de a:hover ( hay un espacio despues de los dos puntos )
2.- los enlaces se ven en azul por defecto.
3. - El pie de página queda mal

Iconos cabecera.
Voy a eliminar el enlace de facebook y google plus, voy a añadir el de la lista de correo, asi quedan los que realmente usamos
twiter, la lista, github y el rss

Página de contacto:
la voy a cambiar por una pagina de información con los enlaces a twiter, y la lista, que son los sitios de contacto del grupo.

Alguien en contra?

**Comment by Osukaru** [comment]
Por mi parte vía libre!!!
------Mensaje original------
De: Daniel González
Para: Oscar Lopez
Asunto: [symfony-madrid] Modificaciones en la web (#6)
Enviado: 28 de mar de 2012 12:36

Hola chicos.

Si nadie tiene nada en contra voy a realizar los siguientes cambios en la web.

CSS, tiene algunos errores,
1.- el netbeans me marca como error a :hover en lugar de a:hover ( hay un espacio despues de los dos puntos )
2.- los enlaces se ven en azul por defecto.
3. - El pie de página queda mal

Iconos cabecera.
Voy a eliminar el enlace de facebook y google plus, voy a añadir el de la lista de correo, asi quedan los que realmente usamos
twiter, la lista, github y el rss

Página de contacto:
la voy a cambiar por una pagina de información con los enlaces a twiter, y la lista, que son los sitios de contacto del grupo.

Alguien en contra?

---

Reply to this email directly or view it on GitHub:
https://github.com/symfony-madrid/symfony-madrid/issues/6

Enviado desde mi BlackBerry® de Vodafone

**Comment by egulias** [comment]
+1

**Comment by desarrolla2** [comment]
Listo, he añadido algunas detalles, paginas de error, titulos y alguna URL personalizada.

En cuanto llege a casa hago push!
