### ISSUE TITLE
Widget para la lista de correo

### ISSUE THREAD

**Issue by desarrolla2** [symfony-madrid/symfony-madrid#7]
No se si existe una api, pero igual que tenemos el widget de twiter, podríamos poner otro con los temas de la lista de correo.

**Comment by egulias** [comment]
No existe API, hay una feature request abierta desde 2007: http://code.google.com/p/gdata-issues/issues/detail?id=27#makechanges
Y como mucho hay un scraper de 1 año de antigüedad: https://github.com/auzigog/google-groups-php-api

**Comment by desarrolla2** [comment]
No existe API, pero se purse consultation a traves de xml. Luego te Paso el
link por q es chungo de enconyrar
On Apr 8, 2012 5:39 PM, "Eduardo Gulias Davis" <
reply@reply.github.com>
wrote:

**Comment by egulias** [comment]
Vale, estupendo. Si me pones el link lo miro.

**Comment by desarrolla2** [comment]
Esta es una versión en XML de los últimos 15 temas:

https://groups.google.com/group/symfony_madrid/feed/rss_v2_0_topics.xml
