### ISSUE TITLE
Widget flicker

### ISSUE THREAD

**Issue by desarrolla2** [symfony-madrid/symfony-madrid#9]
Pues si hacemos alguna fotillo en cada evento, o en los que participemos (ej, codemotion ) los subimos a una cuenta de flicker y que salgan en el sitio web.

**Comment by egulias** [comment]
Tenemos cuenta en flicker? Para poder conectarte hay que pedir un API key en flicker.

**Comment by desarrolla2** [comment]
Creala tu mismo
On Apr 8, 2012 5:31 PM, "Eduardo Gulias Davis" <
reply@reply.github.com>
wrote:

**Comment by egulias** [comment]
Grupo creado: http://www.flickr.com/groups/symfony-madrid/

Sacaré el API Key y hago el widget. Luego te la paso para que la pongas en el parameters.ini

**Comment by egulias** [comment]
Encontré este bundle: https://github.com/ideatosrl/FlickrApiBundle
Es el único que hay para flickr. Lo que no me gusta es como hay que poner las claves. Voy a probarlo y os cuento.
